### ISSUE TITLE
navx_ftc library:  AHRS class exception when 0-length read returned from Core Device Interface Module

### ISSUE THREAD

**Issue by kauailabs** [kauailabs/navxmxp#49]
The below stack trace was provided to the navX-MXP support forum by RB. 

It appears to show a 0-length result being returned (without any other sign of error) from the Core Device Interface Module.  This is an unexpected behavior, but it points to an issue that the code should add some bounds checking in the decodeNavxProcessedData method to handle I2C read data that is less than the expected amount.

**** Log Data ****

02-05 12:29:18.079 17567 17680 E AndroidRuntime: FATAL EXCEPTION: r/w loop: Modern Robotics USB Core Device Interface Module [AL00VBY8]
02-05 12:29:18.079 17567 17680 E AndroidRuntime: Process: com.qualcomm.ftcrobotcontroller, PID: 17567
02-05 12:29:18.079 17567 17680 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=2
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.kauailabs.navx.AHRSProtocol.decodeBinaryUint32(AHRSProtocol.java:685)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.kauailabs.navx.ftc.AHRS$navXIOThread.decodeNavxProcessedData(AHRS.java:1306)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.kauailabs.navx.ftc.AHRS$navXIOThread.ioComplete(AHRS.java:1052)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.kauailabs.navx.ftc.AHRS$DimI2cDeviceReader.portDone(AHRS.java:1688)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.kauailabs.navx.ftc.AHRS$DimI2cDeviceReader.access$600(AHRS.java:1513)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.kauailabs.navx.ftc.AHRS$DimI2cDeviceReader$1.portIsReady(AHRS.java:1546)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.qualcomm.robotcore.hardware.I2cDeviceImpl.portIsReady(I2cDeviceImpl.java:249)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.qualcomm.hardware.modernrobotics.ModernRoboticsUsbDeviceInterfaceModule.readComplete(ModernRoboticsUsbDeviceInterfaceModule.java:932)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.qualcomm.hardware.modernrobotics.comm.ReadWriteRunnableStandard$1.run(ReadWriteRunnableStandard.java:369)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:513)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at com.qualcomm.hardware.modernrobotics.comm.ReadWriteRunnableStandard.run(ReadWriteRunnableStandard.java:304)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-05 12:29:18.079 17567 17680 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)

**Comment by kauailabs** [comment]
Resolved w/commit 09abe90221cb9d0ae104776af037d0b8a7f2d72 (2/10/2017).
